/* tslint:disable */
/* eslint-disable */
/**
 * Hospital Equipment Management API
 * Storage Equipment management for hospital
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xskrabakf@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EquipmentCreate
 */
export interface EquipmentCreate {
    /**
     * Name of the equipment
     * @type {string}
     * @memberof EquipmentCreate
     */
    name: string;
    /**
     * Serial number of the equipment
     * @type {string}
     * @memberof EquipmentCreate
     */
    serialNumber: string;
    /**
     * Manufacturer of the equipment
     * @type {string}
     * @memberof EquipmentCreate
     */
    manufacturer: string;
    /**
     * Model of the equipment
     * @type {string}
     * @memberof EquipmentCreate
     */
    model?: string;
    /**
     * Date when equipment was installed
     * @type {Date}
     * @memberof EquipmentCreate
     */
    installationDate: Date;
    /**
     * Location of the equipment in the hospital
     * @type {string}
     * @memberof EquipmentCreate
     */
    location: string;
    /**
     * Service interval in days
     * @type {number}
     * @memberof EquipmentCreate
     */
    serviceInterval?: number;
    /**
     * Date of last service
     * @type {Date}
     * @memberof EquipmentCreate
     */
    lastService?: Date;
    /**
     * Life expectancy in years
     * @type {number}
     * @memberof EquipmentCreate
     */
    lifeExpectancy?: number;
    /**
     * 
     * @type {string}
     * @memberof EquipmentCreate
     */
    status?: EquipmentCreateStatusEnum;
    /**
     * Additional notes about the equipment
     * @type {string}
     * @memberof EquipmentCreate
     */
    notes?: string;
}


/**
 * @export
 */
export const EquipmentCreateStatusEnum = {
    Operational: 'operational',
    InRepair: 'in_repair',
    Faulty: 'faulty',
    Decommissioned: 'decommissioned'
} as const;
export type EquipmentCreateStatusEnum = typeof EquipmentCreateStatusEnum[keyof typeof EquipmentCreateStatusEnum];


/**
 * Check if a given object implements the EquipmentCreate interface.
 */
export function instanceOfEquipmentCreate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "serialNumber" in value;
    isInstance = isInstance && "manufacturer" in value;
    isInstance = isInstance && "installationDate" in value;
    isInstance = isInstance && "location" in value;

    return isInstance;
}

export function EquipmentCreateFromJSON(json: any): EquipmentCreate {
    return EquipmentCreateFromJSONTyped(json, false);
}

export function EquipmentCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): EquipmentCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'serialNumber': json['serialNumber'],
        'manufacturer': json['manufacturer'],
        'model': !exists(json, 'model') ? undefined : json['model'],
        'installationDate': (new Date(json['installationDate'])),
        'location': json['location'],
        'serviceInterval': !exists(json, 'serviceInterval') ? undefined : json['serviceInterval'],
        'lastService': !exists(json, 'lastService') ? undefined : (new Date(json['lastService'])),
        'lifeExpectancy': !exists(json, 'lifeExpectancy') ? undefined : json['lifeExpectancy'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'notes': !exists(json, 'notes') ? undefined : json['notes'],
    };
}

export function EquipmentCreateToJSON(value?: EquipmentCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'serialNumber': value.serialNumber,
        'manufacturer': value.manufacturer,
        'model': value.model,
        'installationDate': (value.installationDate.toISOString().substr(0,10)),
        'location': value.location,
        'serviceInterval': value.serviceInterval,
        'lastService': value.lastService === undefined ? undefined : (value.lastService.toISOString().substr(0,10)),
        'lifeExpectancy': value.lifeExpectancy,
        'status': value.status,
        'notes': value.notes,
    };
}

