/* tslint:disable */
/* eslint-disable */
/**
 * Hospital Equipment Management API
 * Storage Equipment management for hospital
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xskrabakf@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EquipmentItem
 */
export interface EquipmentItem {
    /**
     * 
     * @type {string}
     * @memberof EquipmentItem
     */
    id: string;
    /**
     * Name of the equipment
     * @type {string}
     * @memberof EquipmentItem
     */
    name: string;
    /**
     * Serial number of the equipment
     * @type {string}
     * @memberof EquipmentItem
     */
    serialNumber: string;
    /**
     * Manufacturer of the equipment
     * @type {string}
     * @memberof EquipmentItem
     */
    manufacturer: string;
    /**
     * Model of the equipment
     * @type {string}
     * @memberof EquipmentItem
     */
    model?: string;
    /**
     * Date when equipment was installed
     * @type {Date}
     * @memberof EquipmentItem
     */
    installationDate: Date;
    /**
     * Location of the equipment in the hospital
     * @type {string}
     * @memberof EquipmentItem
     */
    location: string;
    /**
     * Service interval in days
     * @type {number}
     * @memberof EquipmentItem
     */
    serviceInterval?: number;
    /**
     * Date of last service
     * @type {Date}
     * @memberof EquipmentItem
     */
    lastService?: Date;
    /**
     * Date of next scheduled service
     * @type {Date}
     * @memberof EquipmentItem
     */
    nextService?: Date;
    /**
     * Life expectancy in years
     * @type {number}
     * @memberof EquipmentItem
     */
    lifeExpectancy?: number;
    /**
     * 
     * @type {string}
     * @memberof EquipmentItem
     */
    status?: EquipmentItemStatusEnum;
    /**
     * Additional notes about the equipment
     * @type {string}
     * @memberof EquipmentItem
     */
    notes?: string;
}


/**
 * @export
 */
export const EquipmentItemStatusEnum = {
    Operational: 'operational',
    InRepair: 'in_repair',
    Faulty: 'faulty',
    Decommissioned: 'decommissioned'
} as const;
export type EquipmentItemStatusEnum = typeof EquipmentItemStatusEnum[keyof typeof EquipmentItemStatusEnum];


/**
 * Check if a given object implements the EquipmentItem interface.
 */
export function instanceOfEquipmentItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "serialNumber" in value;
    isInstance = isInstance && "manufacturer" in value;
    isInstance = isInstance && "installationDate" in value;
    isInstance = isInstance && "location" in value;

    return isInstance;
}

export function EquipmentItemFromJSON(json: any): EquipmentItem {
    return EquipmentItemFromJSONTyped(json, false);
}

export function EquipmentItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): EquipmentItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'serialNumber': json['serialNumber'],
        'manufacturer': json['manufacturer'],
        'model': !exists(json, 'model') ? undefined : json['model'],
        'installationDate': (new Date(json['installationDate'])),
        'location': json['location'],
        'serviceInterval': !exists(json, 'serviceInterval') ? undefined : json['serviceInterval'],
        'lastService': !exists(json, 'lastService') ? undefined : (new Date(json['lastService'])),
        'nextService': !exists(json, 'nextService') ? undefined : (new Date(json['nextService'])),
        'lifeExpectancy': !exists(json, 'lifeExpectancy') ? undefined : json['lifeExpectancy'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'notes': !exists(json, 'notes') ? undefined : json['notes'],
    };
}

export function EquipmentItemToJSON(value?: EquipmentItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'serialNumber': value.serialNumber,
        'manufacturer': value.manufacturer,
        'model': value.model,
        'installationDate': (value.installationDate.toISOString().substr(0,10)),
        'location': value.location,
        'serviceInterval': value.serviceInterval,
        'lastService': value.lastService === undefined ? undefined : (value.lastService.toISOString().substr(0,10)),
        'nextService': value.nextService === undefined ? undefined : (value.nextService.toISOString().substr(0,10)),
        'lifeExpectancy': value.lifeExpectancy,
        'status': value.status,
        'notes': value.notes,
    };
}

