/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SteqApp {
        "basePath": string;
    }
    interface SteqOrdersList {
    }
}
declare global {
    interface HTMLSteqAppElement extends Components.SteqApp, HTMLStencilElement {
    }
    var HTMLSteqAppElement: {
        prototype: HTMLSteqAppElement;
        new (): HTMLSteqAppElement;
    };
    interface HTMLSteqOrdersListElement extends Components.SteqOrdersList, HTMLStencilElement {
    }
    var HTMLSteqOrdersListElement: {
        prototype: HTMLSteqOrdersListElement;
        new (): HTMLSteqOrdersListElement;
    };
    interface HTMLElementTagNameMap {
        "steq-app": HTMLSteqAppElement;
        "steq-orders-list": HTMLSteqOrdersListElement;
    }
}
declare namespace LocalJSX {
    interface SteqApp {
        "basePath"?: string;
    }
    interface SteqOrdersList {
    }
    interface IntrinsicElements {
        "steq-app": SteqApp;
        "steq-orders-list": SteqOrdersList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "steq-app": LocalJSX.SteqApp & JSXBase.HTMLAttributes<HTMLSteqAppElement>;
            "steq-orders-list": LocalJSX.SteqOrdersList & JSXBase.HTMLAttributes<HTMLSteqOrdersListElement>;
        }
    }
}
